# ==============================================================================
# CONFIGURACIÓN DE GESTOS DEL TOUCHPAD 
# ==============================================================================

# Gesto principal: Deslizar 3 dedos hacia abajo invoca el Launchpad de Rofi a pantalla completa
gesture swipe down 3 rofi -show drun -theme ~/.config/rofi/launchpad.rasi

# (Opcional) Si quieres que deslizar 3 dedos hacia arriba mate a Rofi por si te arrepientes:
# gesture swipe up 3 killall rofi